// EFFECTS REGISTRY - All 100 effects with full metadata
// The brain uses this to pick the right effects for each mode

import { Effect, VideoModeType } from './schema'

export const EFFECTS_REGISTRY: Effect[] = [
  // ==================== ZOOM EFFECTS (10) ====================
  {
    id: 'zoom_pulse',
    name: 'Zoom Pulse',
    description: 'Quick zoom in and out for emphasis on key moments',
    category: 'zoom',
    layer: 'video',
    priority: 80,
    modes: ['mrbeast', 'tiktok', 'shorts', 'gaming', 'trailer'],
    conflicts: ['zoom_in_slow', 'zoom_out_slow'],
    pairsWith: ['flash_white', 'bass_pulse'],
    triggers: {
      keywords: ['wow', 'amazing', 'incredible', 'insane', 'crazy', 'what', 'omg', 'no way'],
      punctuation: ['!', '?!'],
      sentiment: 'positive',
      weight: 0.8,
      maxPerMinute: 15,
      minGapFrames: 20,
    },
    timing: { minDuration: 10, maxDuration: 25, defaultDuration: 16, cooldown: 30, attackFrames: 3, releaseFrames: 5 },
    props: { intensity: 1.15 },
    variants: ['subtle', 'medium', 'intense'],
    assets: { required: [], optional: [] },
  },
  {
    id: 'zoom_in_slow',
    name: 'Slow Zoom In',
    description: 'Cinematic Ken Burns style slow push in',
    category: 'zoom',
    layer: 'video',
    priority: 70,
    modes: ['lemmino', 'documentary', 'cinematic', 'truecrime', 'naturedoc', 'podcast', 'aesthetic'],
    conflicts: ['zoom_pulse', 'zoom_punch', 'shake_heavy'],
    pairsWith: ['letterbox', 'vignette', 'cinematic'],
    triggers: {
      keywords: ['story', 'history', 'began', 'discovered', 'years', 'ancient', 'mystery'],
      punctuation: ['...'],
      sentiment: 'neutral',
      weight: 0.7,
      maxPerMinute: 4,
      minGapFrames: 150,
    },
    timing: { minDuration: 60, maxDuration: 300, defaultDuration: 150, cooldown: 180, attackFrames: 0, releaseFrames: 0 },
    props: { target: 1.2 },
    variants: ['subtle', 'medium'],
    assets: { required: [], optional: [] },
  },
  {
    id: 'zoom_out_slow',
    name: 'Slow Zoom Out',
    description: 'Revealing shot that pulls back slowly',
    category: 'zoom',
    layer: 'video',
    priority: 65,
    modes: ['lemmino', 'documentary', 'cinematic', 'naturedoc'],
    conflicts: ['zoom_in_slow', 'zoom_pulse'],
    pairsWith: ['letterbox', 'vignette'],
    triggers: {
      keywords: ['reveal', 'finally', 'conclusion', 'end', 'result', 'outcome'],
      punctuation: [],
      sentiment: 'neutral',
      weight: 0.6,
      maxPerMinute: 3,
      minGapFrames: 200,
    },
    timing: { minDuration: 60, maxDuration: 250, defaultDuration: 120, cooldown: 200, attackFrames: 0, releaseFrames: 0 },
    props: { start: 1.3 },
    variants: ['subtle', 'dramatic'],
    assets: { required: [], optional: [] },
  },
  {
    id: 'zoom_punch',
    name: 'Zoom Punch',
    description: 'MrBeast style hard zoom with spring animation',
    category: 'zoom',
    layer: 'video',
    priority: 90,
    modes: ['mrbeast', 'tiktok', 'shorts', 'gaming', 'trailer', 'vlog'],
    conflicts: ['zoom_in_slow', 'zoom_out_slow'],
    pairsWith: ['flash_white', 'text_pop', 'shake_heavy'],
    triggers: {
      keywords: ['million', 'thousand', 'won', 'lost', 'dead', 'killed', 'destroyed', 'epic', 'insane', 'money'],
      punctuation: ['!', '!!'],
      sentiment: 'any',
      weight: 0.9,
      maxPerMinute: 25,
      minGapFrames: 15,
    },
    timing: { minDuration: 6, maxDuration: 15, defaultDuration: 8, cooldown: 20, attackFrames: 2, releaseFrames: 4 },
    props: { intensity: 1.4 },
    variants: ['light', 'heavy', 'extreme'],
    assets: { required: [], optional: [] },
  },
  {
    id: 'zoom_bounce',
    name: 'Zoom Bounce',
    description: 'Bouncy zoom effect with spring physics',
    category: 'zoom',
    layer: 'video',
    priority: 75,
    modes: ['tiktok', 'shorts', 'vlog', 'gaming'],
    conflicts: ['zoom_in_slow'],
    pairsWith: ['text_bounce', 'emoji_rain'],
    triggers: {
      keywords: ['bounce', 'jump', 'hop', 'boing', 'spring', 'fun'],
      punctuation: [],
      sentiment: 'positive',
      weight: 0.7,
      maxPerMinute: 12,
      minGapFrames: 25,
    },
    timing: { minDuration: 15, maxDuration: 40, defaultDuration: 25, cooldown: 35, attackFrames: 5, releaseFrames: 10 },
    props: { intensity: 1.2 },
    variants: ['subtle', 'bouncy'],
    assets: { required: [], optional: [] },
  },
  {
    id: 'dolly_zoom',
    name: 'Dolly Zoom',
    description: 'Hitchcock vertigo effect - zoom while moving',
    category: 'zoom',
    layer: 'video',
    priority: 60,
    modes: ['cinematic', 'trailer', 'truecrime'],
    conflicts: ['zoom_pulse', 'shake_heavy'],
    pairsWith: ['dramatic', 'vignette'],
    triggers: {
      keywords: ['realize', 'shock', 'discover', 'horror', 'fear', 'vertigo'],
      punctuation: [],
      sentiment: 'negative',
      weight: 0.5,
      maxPerMinute: 2,
      minGapFrames: 300,
    },
    timing: { minDuration: 45, maxDuration: 120, defaultDuration: 60, cooldown: 300, attackFrames: 0, releaseFrames: 0 },
    props: {},
    variants: [],
    assets: { required: [], optional: [] },
  },
  {
    id: 'zoom_rotate',
    name: 'Zoom Rotate',
    description: 'Zoom with subtle rotation for dynamic feel',
    category: 'zoom',
    layer: 'video',
    priority: 55,
    modes: ['gaming', 'trailer', 'mrbeast'],
    conflicts: ['zoom_in_slow'],
    pairsWith: ['flash_color'],
    triggers: {
      keywords: ['spin', 'twist', 'turn', 'rotate', 'crazy'],
      punctuation: [],
      sentiment: 'any',
      weight: 0.5,
      maxPerMinute: 6,
      minGapFrames: 60,
    },
    timing: { minDuration: 12, maxDuration: 30, defaultDuration: 18, cooldown: 60, attackFrames: 3, releaseFrames: 5 },
    props: {},
    variants: ['clockwise', 'counterclockwise'],
    assets: { required: [], optional: [] },
  },
  {
    id: 'zoom_focus',
    name: 'Zoom Focus',
    description: 'Zoom to specific point for tutorials',
    category: 'zoom',
    layer: 'video',
    priority: 70,
    modes: ['tutorial', 'course', 'vox'],
    conflicts: [],
    pairsWith: ['spotlight', 'arrow_pointer'],
    triggers: {
      keywords: ['look', 'see', 'notice', 'here', 'this', 'click', 'button', 'focus'],
      punctuation: [],
      sentiment: 'neutral',
      weight: 0.8,
      maxPerMinute: 8,
      minGapFrames: 45,
    },
    timing: { minDuration: 30, maxDuration: 90, defaultDuration: 45, cooldown: 50, attackFrames: 10, releaseFrames: 10 },
    props: { x: 50, y: 50 },
    variants: [],
    assets: { required: [], optional: [] },
  },
  {
    id: 'zoom_shake',
    name: 'Zoom Shake',
    description: 'Zoom combined with camera shake for impact',
    category: 'zoom',
    layer: 'video',
    priority: 75,
    modes: ['mrbeast', 'gaming', 'trailer'],
    conflicts: ['zoom_in_slow'],
    pairsWith: ['flash_white', 'bass_pulse'],
    triggers: {
      keywords: ['explosion', 'crash', 'boom', 'impact', 'hit', 'smash'],
      punctuation: ['!'],
      sentiment: 'any',
      weight: 0.7,
      maxPerMinute: 10,
      minGapFrames: 30,
    },
    timing: { minDuration: 8, maxDuration: 20, defaultDuration: 12, cooldown: 40, attackFrames: 2, releaseFrames: 6 },
    props: {},
    variants: [],
    assets: { required: [], optional: [] },
  },
  {
    id: 'zoom_glitch',
    name: 'Zoom Glitch',
    description: 'Glitchy zoom with digital artifacts',
    category: 'zoom',
    layer: 'video',
    priority: 50,
    modes: ['gaming', 'tiktok', 'shorts'],
    conflicts: ['zoom_in_slow', 'cinematic'],
    pairsWith: ['glitch_transition', 'text_glitch'],
    triggers: {
      keywords: ['error', 'glitch', 'bug', 'broken', 'hack', 'virus'],
      punctuation: [],
      sentiment: 'negative',
      weight: 0.5,
      maxPerMinute: 5,
      minGapFrames: 60,
    },
    timing: { minDuration: 10, maxDuration: 30, defaultDuration: 15, cooldown: 60, attackFrames: 0, releaseFrames: 0 },
    props: {},
    variants: [],
    assets: { required: [], optional: [] },
  },

  // ==================== TEXT EFFECTS (13) ====================
  {
    id: 'text_pop',
    name: 'Text Pop',
    description: 'Text that pops in with scale animation',
    category: 'text',
    layer: 'text',
    priority: 85,
    modes: ['mrbeast', 'tiktok', 'shorts', 'gaming', 'vlog'],
    conflicts: [],
    pairsWith: ['zoom_punch', 'flash_white'],
    triggers: {
      keywords: ['wow', 'amazing', 'omg', 'what', 'no', 'yes', 'win', 'lose'],
      punctuation: ['!', '?'],
      sentiment: 'any',
      weight: 0.9,
      maxPerMinute: 20,
      minGapFrames: 15,
    },
    timing: { minDuration: 20, maxDuration: 60, defaultDuration: 30, cooldown: 20, attackFrames: 5, releaseFrames: 5 },
    props: { text: '', color: '#ffffff', size: 120 },
    variants: ['small', 'medium', 'large'],
    assets: { required: [], optional: [] },
  },
  {
    id: 'text_slide_in',
    name: 'Text Slide In',
    description: 'Text slides in from side of screen',
    category: 'text',
    layer: 'text',
    priority: 70,
    modes: ['vox', 'documentary', 'tutorial', 'course'],
    conflicts: [],
    pairsWith: ['zoom_in_slow'],
    triggers: {
      keywords: ['breaking', 'news', 'update', 'fact', 'statistic', 'number'],
      punctuation: [':'],
      sentiment: 'neutral',
      weight: 0.7,
      maxPerMinute: 10,
      minGapFrames: 30,
    },
    timing: { minDuration: 45, maxDuration: 120, defaultDuration: 60, cooldown: 40, attackFrames: 15, releaseFrames: 10 },
    props: { text: '', from: 'left' },
    variants: ['left', 'right'],
    assets: { required: [], optional: [] },
  },
  {
    id: 'text_typewriter',
    name: 'Text Typewriter',
    description: 'Text types out character by character',
    category: 'text',
    layer: 'text',
    priority: 65,
    modes: ['tutorial', 'course', 'truecrime', 'documentary'],
    conflicts: ['text_pop'],
    pairsWith: ['spotlight'],
    triggers: {
      keywords: ['code', 'command', 'terminal', 'type', 'write', 'message'],
      punctuation: [],
      sentiment: 'neutral',
      weight: 0.6,
      maxPerMinute: 5,
      minGapFrames: 90,
    },
    timing: { minDuration: 60, maxDuration: 180, defaultDuration: 90, cooldown: 100, attackFrames: 0, releaseFrames: 15 },
    props: { text: '', speed: 2 },
    variants: ['slow', 'medium', 'fast'],
    assets: { required: [], optional: [] },
  },
  {
    id: 'text_glitch',
    name: 'Text Glitch',
    description: 'Glitchy distorted text effect',
    category: 'text',
    layer: 'text',
    priority: 60,
    modes: ['gaming', 'tiktok', 'shorts'],
    conflicts: ['text_typewriter'],
    pairsWith: ['zoom_glitch', 'glitch_transition'],
    triggers: {
      keywords: ['error', 'glitch', 'bug', 'crash', 'hack', 'system'],
      punctuation: [],
      sentiment: 'negative',
      weight: 0.6,
      maxPerMinute: 8,
      minGapFrames: 45,
    },
    timing: { minDuration: 15, maxDuration: 45, defaultDuration: 25, cooldown: 50, attackFrames: 0, releaseFrames: 0 },
    props: { text: '' },
    variants: [],
    assets: { required: [], optional: [] },
  },
  {
    id: 'text_bounce',
    name: 'Text Bounce',
    description: 'Bouncy text animation with spring physics',
    category: 'text',
    layer: 'text',
    priority: 75,
    modes: ['tiktok', 'shorts', 'vlog', 'gaming'],
    conflicts: [],
    pairsWith: ['zoom_bounce', 'emoji_rain'],
    triggers: {
      keywords: ['bounce', 'jump', 'boing', 'hop', 'spring', 'fun', 'yay'],
      punctuation: ['!'],
      sentiment: 'positive',
      weight: 0.7,
      maxPerMinute: 15,
      minGapFrames: 25,
    },
    timing: { minDuration: 25, maxDuration: 60, defaultDuration: 35, cooldown: 30, attackFrames: 8, releaseFrames: 5 },
    props: { text: '' },
    variants: [],
    assets: { required: [], optional: [] },
  },
  {
    id: 'text_countdown',
    name: 'Text Countdown',
    description: '3, 2, 1 countdown animation',
    category: 'text',
    layer: 'text',
    priority: 80,
    modes: ['mrbeast', 'gaming', 'trailer', 'shorts'],
    conflicts: [],
    pairsWith: ['bass_pulse'],
    triggers: {
      keywords: ['countdown', 'ready', 'start', 'begin', 'go', 'three', 'two', 'one'],
      punctuation: [],
      sentiment: 'positive',
      weight: 0.8,
      maxPerMinute: 2,
      minGapFrames: 300,
    },
    timing: { minDuration: 90, maxDuration: 120, defaultDuration: 100, cooldown: 300, attackFrames: 0, releaseFrames: 0 },
    props: { start: 3 },
    variants: ['3-2-1', '5-4-3-2-1', '10-second'],
    assets: { required: [], optional: [] },
  },
  {
    id: 'text_neon',
    name: 'Text Neon',
    description: 'Neon glow text with pulsing effect',
    category: 'text',
    layer: 'text',
    priority: 65,
    modes: ['gaming', 'tiktok', 'aesthetic'],
    conflicts: [],
    pairsWith: ['neon_glow'],
    triggers: {
      keywords: ['neon', 'glow', 'light', 'bright', 'shine', 'electric'],
      punctuation: [],
      sentiment: 'positive',
      weight: 0.6,
      maxPerMinute: 8,
      minGapFrames: 50,
    },
    timing: { minDuration: 30, maxDuration: 90, defaultDuration: 45, cooldown: 60, attackFrames: 10, releaseFrames: 10 },
    props: { text: '', color: '#00ffff' },
    variants: ['cyan', 'pink', 'green', 'purple'],
    assets: { required: [], optional: [] },
  },
  {
    id: 'text_explode',
    name: 'Text Explode',
    description: 'Letters explode outward from center',
    category: 'text',
    layer: 'text',
    priority: 70,
    modes: ['mrbeast', 'trailer', 'gaming'],
    conflicts: [],
    pairsWith: ['flash_white', 'confetti'],
    triggers: {
      keywords: ['boom', 'explode', 'blast', 'burst', 'bang', 'kaboom'],
      punctuation: ['!'],
      sentiment: 'any',
      weight: 0.7,
      maxPerMinute: 6,
      minGapFrames: 60,
    },
    timing: { minDuration: 20, maxDuration: 40, defaultDuration: 25, cooldown: 70, attackFrames: 5, releaseFrames: 0 },
    props: { text: '' },
    variants: [],
    assets: { required: [], optional: [] },
  },
  {
    id: 'text_wave',
    name: 'Text Wave',
    description: 'Wavy text animation with color shift',
    category: 'text',
    layer: 'text',
    priority: 60,
    modes: ['tiktok', 'aesthetic', 'vlog'],
    conflicts: [],
    pairsWith: ['gradient_overlay'],
    triggers: {
      keywords: ['wave', 'flow', 'smooth', 'chill', 'vibe', 'mood'],
      punctuation: [],
      sentiment: 'positive',
      weight: 0.5,
      maxPerMinute: 6,
      minGapFrames: 60,
    },
    timing: { minDuration: 45, maxDuration: 120, defaultDuration: 60, cooldown: 70, attackFrames: 10, releaseFrames: 10 },
    props: { text: '' },
    variants: [],
    assets: { required: [], optional: [] },
  },
  {
    id: 'text_3d',
    name: 'Text 3D',
    description: '3D extruded text with rotation',
    category: 'text',
    layer: 'text',
    priority: 55,
    modes: ['trailer', 'gaming'],
    conflicts: [],
    pairsWith: ['dramatic'],
    triggers: {
      keywords: ['epic', 'legendary', 'ultimate', 'supreme', 'mega', 'ultra'],
      punctuation: [],
      sentiment: 'positive',
      weight: 0.5,
      maxPerMinute: 4,
      minGapFrames: 90,
    },
    timing: { minDuration: 45, maxDuration: 90, defaultDuration: 60, cooldown: 100, attackFrames: 15, releaseFrames: 15 },
    props: { text: '' },
    variants: [],
    assets: { required: [], optional: [] },
  },
  {
    id: 'text_shadow',
    name: 'Text Shadow',
    description: 'Dramatic shadow text effect',
    category: 'text',
    layer: 'text',
    priority: 65,
    modes: ['cinematic', 'truecrime', 'trailer'],
    conflicts: [],
    pairsWith: ['dramatic', 'vignette'],
    triggers: {
      keywords: ['dark', 'shadow', 'hidden', 'secret', 'mystery'],
      punctuation: [],
      sentiment: 'negative',
      weight: 0.6,
      maxPerMinute: 6,
      minGapFrames: 60,
    },
    timing: { minDuration: 30, maxDuration: 90, defaultDuration: 45, cooldown: 70, attackFrames: 10, releaseFrames: 10 },
    props: { text: '' },
    variants: [],
    assets: { required: [], optional: [] },
  },
  {
    id: 'text_outline',
    name: 'Text Outline',
    description: 'Outlined text with no fill',
    category: 'text',
    layer: 'text',
    priority: 60,
    modes: ['gaming', 'tiktok', 'vlog'],
    conflicts: [],
    pairsWith: ['neon_glow'],
    triggers: {
      keywords: ['outline', 'border', 'edge', 'frame'],
      punctuation: [],
      sentiment: 'neutral',
      weight: 0.5,
      maxPerMinute: 8,
      minGapFrames: 45,
    },
    timing: { minDuration: 25, maxDuration: 60, defaultDuration: 35, cooldown: 50, attackFrames: 8, releaseFrames: 8 },
    props: { text: '', color: '#00ffff' },
    variants: [],
    assets: { required: [], optional: [] },
  },
  {
    id: 'text_gradient',
    name: 'Text Gradient',
    description: 'Rainbow gradient text with animation',
    category: 'text',
    layer: 'text',
    priority: 65,
    modes: ['tiktok', 'shorts', 'aesthetic'],
    conflicts: [],
    pairsWith: ['gradient_overlay'],
    triggers: {
      keywords: ['rainbow', 'colorful', 'pride', 'gradient', 'spectrum'],
      punctuation: [],
      sentiment: 'positive',
      weight: 0.6,
      maxPerMinute: 6,
      minGapFrames: 60,
    },
    timing: { minDuration: 30, maxDuration: 90, defaultDuration: 45, cooldown: 70, attackFrames: 10, releaseFrames: 10 },
    props: { text: '' },
    variants: [],
    assets: { required: [], optional: [] },
  },

  // ==================== MORE EFFECTS CONTINUE... ====================
  // Due to length, I'll create the remaining 77 effects in a separate file
]

// Export helper to get effect by ID
export const getEffectById = (id: string): Effect | undefined => {
  return EFFECTS_REGISTRY.find(e => e.id === id)
}

// Export all effect IDs
export const ALL_EFFECT_IDS = EFFECTS_REGISTRY.map(e => e.id)

export default EFFECTS_REGISTRY

